### ISSUE TITLE
is motif "M1" correctly implemented?

### ISSUE THREAD

**Issue by xiaohan2012** [arbenson/higher-order-organization-matlab#2]
First of all, thanks for this interesting work as well as the code accompanied. 

While trying to run the code, I used a very simple graph as a test case:

```
>> A = [[0, 1, 0]; [0, 0, 1]; [1, 0, 0]]  % basically an M1 instance according to the "motif table" at https://snap.stanford.edu/higher-order/code.html

A =

     0     1     0
     0     0     1
     1     0     0

>> MotifAdjacency(A, 'm1')

ans =

     0     0     0
     0     0     0
     0     0     0
```

If I understand the construction of motif adjacency matrix correctly, the expected output should be:

```
     0     1     1
     1     0     1
     1     1     0
```

because the graph is a M1 instance, thus all nodes should be connected in the motif graph.

Am I missing something? Thanks!

PS:

- My matlab version is `9.5.0.944444 (R2018b)`
- I would implement `M1` as:

```
function W = M1(A)
  [~, U, ~] = DirectionalBreakup(A);
  C = (U * U) .* U';
  W = C + C'
end
```

**Comment by arbenson** [comment]
It was not implemented correctly.
(cf. Table 2.1 here: https://arxiv.org/pdf/1802.06820.pdf)

Fixed with https://github.com/arbenson/higher-order-organization-matlab/commit/3b5be032e625dc087cdf05832c86febaf527b14d

Thank you!
